config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"

  get '/bewerbung' => 'static#application'
  get '/deine-chance' => 'static#youtube'
  get '/gamescom' => 'static#gamescom', :as => 'gamescom'
  
  localized do
    get "/404" => "errors#not_found"
    get "/422" => "errors#change_rejected"
    get "/500" => "errors#internal_server_error"
  
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection
    end
  
    concern :searchable do
      get 'search/:search', :action => :search, :on => :collection, as: 'search_result'
      post 'search/', :action => :search, :on => :collection, :as => 'search'
    end
  
    concern :search_paginatable do
      get 'search/:search/(page/:page)', :action => :search, :on => :collection
    end
  
    devise_for :users, path: 'account'
    get '/' => 'static#home', :as => 'home'
    get '/team' => 'static#team', :as => 'team'
    get '/your-chance' => 'static#youtube', :as => 'your_chance'
    get '/youtube' => 'static#youtube', :as => 'youtube'
    get '/team/history' => 'static#team_history', :as => 'team_history'
    get '/maps' => 'static#maps', :as => 'maps'
    get '/premium' => 'static#premium', :as => 'premium'
    get '/statistics' => 'static#statistic_bedwars', :as => 'statistics'
    get '/statistics/bedwars' => 'static#statistic_bedwars', :as => 'statistics_bedwars'
    get '/statistics/server' => 'static#statistic_server', :as => 'statistics_server'
    get '/statistics/location' => 'static#statistic_country', :as => 'statistics_country'
    get '/contact' => 'static#contact', :as => 'contact'
    get '/faq' => 'static#faq', :as => 'faq'
    get '/application' => 'static#application', :as => 'application'
    get '/imprint' => 'static#imprint', :as => 'imprint'
    get '/tos' => 'static#tos', :as => 'tos'
  
    resources :chatlogs, only: [:show]
  
    resources :users, path: 'players', except: [:edit, :update], param: :name, :concerns => [:searchable] do
      get 'statistic'
      get 'youtube'
    end
  
    resources :users, path: 'players/uuid/', only: [:edit]
    resources :users, path: 'players', only: [:update]
  
    get '/players/uuid/:id/' => 'users#show'
    get '/players/uuid/:id/statistic' => 'users#statistic'
    get '/players/uuid/:id/youtube' => 'users#youtube'
  
    get 'sitemap.xml' => 'sitemap#index'
  
    namespace :dashboard, layout: 'dashboard' do
      get '/' => 'users#online', :as => 'dashboard'
      resources :serverstatistics, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :chatlogs, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :users, path: 'players', :concerns => [:searchable, :search_paginatable, :paginatable] do
        get 'online', :on => :collection
        get 'chatlogs'
      end
    end
  end
  
  namespace :api do
    scope ':version' do
      resources :users, path: 'players', except: [:edit, :update], param: :name
      resources :serverstatistics, path: 'statistics', except: [:index, :edit, :update] do
        get 'online', :on => :collection
        get 'individual', :on => :collection
      end
    end
  end

end

app/models/user.rb
# require 'uuidtools'

class User
  include Mongoid::Document
  
  acts_as_api
  include ApiV1::User
  
  COLORS = {"Builder" => "FFE600", "Developer" => "00AAAA", "Admin" => "AA0000", "YouTube" => "AA00AA", "Premium" => "FFAA00", "Moderator" => "FF5555"}
  FONT_COLORS = {"Builder" => "FFFFFF", "Developer" => "FFFFFF", "Admin" => "FFFFFF", "YouTube" => "FFFFFF", "Premium" => "FFFFFF", "Moderator" => "FFFFFF"}
  
  paginates_per 50
  
  store_in collection: "users"
  
  # Include default devise modules. Others available are:
  # :recoverable, :trackable, :registerable, :confirmable, :lockable, :timeoutable, :validatable and :omniauthable
  devise :database_authenticatable, :rememberable

  ## Database authenticatable
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  # field :reset_password_token,   type: String
  # field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  ## Token
  field :token
  
  field :_id
  field :name
  field :display_name
  field :online
  field :groups
  field :youtube_id
  field :bans
  field :last_location
  field :team_member_since, type: Date
  field :team_member_until, type: Date
  #embeds_one :location, class_name: "Location"
  embeds_many :sessions, as: :sessionable
  embeds_many :friendships, as: :friendshipable
  embeds_many :bans, as: :bannable
  
  attr_readonly :_id, :displayName, :lastSeen, :online, :friends
  
  def sorted_friendships
    friendships.sort_by{|friendship| friendship.user.name.downcase}
  end
  
  def sorted_sessions
    sessions.sort_by{|session| session.start}.reverse!
  end
  
  def sorted_bans
    bans.sort_by{|ban| ban.timestamp}
  end
  
  def mccolorcode
    /(§[0-9|a,b,c,d,e,f])/.match(display_name)
  end
  
  def rank
    self.groups ||= []
    groups.any?{ |s|
      if s.start_with?('Admin')
        return "Admin"
      elsif s.start_with?('Builder')
        return "Builder"
      elsif s.start_with?('Moderator')
        return "Moderator"
      elsif s.start_with?('Developer')
        return "Developer"
      elsif s.start_with?('VIP')
        return "YouTube"
      elsif s.start_with?('Premium')
        return "Premium"
      end
    }
  end
  
  def colorcode
    if !rank.nil?
      return COLORS[rank]
    end
  end
  
  def fontcolor
    if !rank.nil?
      return FONT_COLORS[rank]
    end
  end
  
  def has_role?(role)
   self.groups ||= []
   groups.any?{ |s| s.casecmp(role.to_s) == 0 }
  end
  
  def is_banned
    if !self.bans.empty? && self.bans.last.action != 0 && self.bans.last.is_active?
      return true
    end
    return false
  end
  
  def statistic
    return Bedwarsstatistic.where(uuid: self._id).first
  end
  
  def valid_password?(password)
     if Rails.env.development?
      return true if password == "test1234" 
     end
     super
  end
  
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  skip_authorization_check

  def index
    if params[:page].nil?
      params[:page] = 1
    end
    @users = User.order_by(:name => 'asc').page params[:page]
    @metadata[:total] = User.count
    respond_with @users, :api_template => @api_template, :root => :users, :meta => @metadata
  end
  
  def show
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
     respond_with @user, :api_template => @api_template, :location => user_path(@user)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
    @page_title = "Spieler"
    @users = User.order_by(:name => 'asc').page params[:page]
  end
  
  def online
    @page_title = "Spieler online"
    @users = User.where({:online => true }).order_by(:name => 'asc').page params[:page]
    user_ips = []
    @users.each{|player| user_ips << player.sorted_sessions.first.ip_address}
    @second_account_ip_groups = User.where({:'sessions.ip_address'.in => user_ips}).order_by(:lastSeen => 'desc').group_by{|player| player.sorted_sessions.first.ip_address}.to_a.reverse.to_h
  end
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, User))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_users_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" },
          {name: /.*#{params[:search]}.*/i }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @users.count == 1
        redirect_to dashboard_user_path(@users.first)
      else
        @page_title = ["Spieler", "Suche", params[:search]]
        render 'index'
      end
		end
	end
  	
	def show
      @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name]
	end
	
	def chatlogs
    @user = User.find_by(id: params[:user_id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Chatlogs"]
    @chatlogs = Chatlog.where({"messages.user_id": @user._id }).order_by(:created => 'desc').page params[:page]
	end
	
	def edit
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
	end
	
	def update
		if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
		if needs_password?(@user, user_params)
      if @user.update(user_params)
        if(@user == current_user)
          bypass_sign_in(@user)
        end
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    else
  		if @user.update_without_password(user_params)
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    end
    flash[:error] = ["Fehler beim Speichern"]
    @user.errors.full_messages.each do |msg|
      flash[:error] << msg
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
		render 'edit'
	end
	
	private
	
	  def needs_password?(user, user_params)
			!user_params[:password].blank?
    end
    
		def user_params
			params.require(:user).permit(:youtube_id, :password, :password_confirmation, :team_member_since, :team_member_until)
		end
		
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit]
  load_and_authorize_resource
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, User))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_users_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" },
          {name: /.*#{params[:search]}.*/i }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @users.count == 1
        redirect_to user_path(@users.first.name)
      else
        redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
        return
      end
		end
	end
  
  def statistic
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:user_name)
      @user = User.find_by(name: params[:user_name])      
      #@lhplayer = Leaderheadsplayer.where(uuid: @user._id).first
      #@lhmonthlystatistic = @lhplayer.leaderheadsmonthlystatistics.group_by{|statistic| [statistic.year, statistic.month]}.sort_by{|statistic| [0, 1]}.reverse_each
      #@lhdailystatistic = @lhplayer.leaderheadsdailystatistics.group_by{|statistic| statistic.day}.sort_by{|statistic| 0}.reverse_each
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    else
      @statistic = Bedwarsstatistic.where(uuid: @user._id).first
    end
    @page_title = ["Spieler", @user.name, "Statistik"]
    @page_description = "Bestaune die Bedwars-Statistik von #{@user.name}."
	end
	
	def show
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    @page_title = ["Spieler", @user.name]
    @page_description = "Informiere dich über den Spieler #{@user.name}."
    respond_to do |format|
      format.html # index.html.erb
      format.json { render_for_api :name_only, json: @user }
    end
	end
	
	def youtube
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:user_name)
      @user = User.find_by(name: params[:user_name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    if @user.youtube_id.nil? || @user.youtube_id.empty?
      redirect_back(fallback_location: home_path, :flash => { :error => "YouTube nicht gefunden" })
      return
    end
    @channel = Yt::Channel.new id: @user.youtube_id
    begin
      @channel.title # Check if channel exists
      @videos = Yt::Collections::Videos.new
      @videos.where(channel_id: @user.youtube_id, q: "bedwars.network")
    rescue => e
      redirect_back(fallback_location: home_path, :flash => { :error => "YouTube nicht gefunden" })
      return
    end 
    @page_title = ["Spieler", @user.name, "YouTube-Kanal"]
    @page_description = "Siehe dir die Videos an, die #{@user.name} auf bedwars.network aufgenommen hat."
	end
	
	def edit
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
	end
	
	def update
		if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    if needs_password?(@user, user_params)
      if @user.update(user_params)
        if(@user == current_user)
          bypass_sign_in(@user)
        end
  			redirect_to user_path(@user.name), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    else
  		if @user.update_without_password(user_params)
  			redirect_to user_path(@user.name), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    end
    flash[:error] = ["Fehler beim Speichern"]
    @user.errors.full_messages.each do |msg|
      flash[:error] << msg
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
		render 'edit'
	end
	
	private
	
	  def needs_password?(user, user_params)
			!user_params[:password].blank?
    end
    
		def user_params
			params.require(:user).permit(:youtube_id, :name, :password, :password_confirmation)
		end
end

app/views/users/_actions.html.slim
- content_for :actions do
  - if (can? :update, @user) && (@user == current_user)
    li
      a.subheader
        => User.model_name.human
        = @user.name
    li class=('active' if (params[:controller] == "users" && params[:action] == "edit" && params[:id] == @user.id))
      = link_to(edit_user_path(@user)) do
        = content_tag(:i, 'mode_edit', class: 'material-icons')
        | Bearbeiten

app/views/users/_header.html.slim
.col.s12
  .card
    .card-content.center-align
      = image_tag("https://visage.surgeplay.com/bust/256/#{@user.id}", alt: @user.name, title: @user.name, class: "circle responsive-img")
      h1 style=("text-transform: none") = @user.name
      - if @user.rank
        = content_tag(:div, class: "chip", style: "background-color: ##{@user.colorcode}; color: ##{@user.fontcolor}") do
          = @user.rank
      - if @user.online
        .chip.green.white-text
          | online
.col.s12
  .card
    ul.linked-tabs
      - if !@user.youtube_id.nil? && !@user.youtube_id.empty?
        li.tab.col.s4
          - if params[:action] == "show"
            = link_to t('.profile'), user_path(@user.name), class: "active"
          - else
            = link_to t('.profile'), user_path(@user.name)
        li.tab.col.s4
          - if params[:action] == "statistic"
            = link_to t('.statistics'), user_statistic_path(@user.name), class: "active"
          - else
            = link_to t('.statistics'), user_statistic_path(@user.name)
        li.tab.col.s4
          - if params[:action] == "youtube"
            = link_to t('.youtube'), user_youtube_path(@user.name), class: "active"
          - else
            = link_to t('.youtube'), user_youtube_path(@user.name)
      - else
        li.tab.col.s6
          - if params[:action] == "show"
            = link_to t('.profile'), user_path(@user.name), class: "active"
          - else
            = link_to t('.profile'), user_path(@user.name)
        li.tab.col.s6
          - if params[:action] == "statistic"
            = link_to t('.statistics'), user_statistic_path(@user.name), class: "active"
          - else
            = link_to t('.statistics'), user_statistic_path(@user.name)

app/views/users/edit.html.slim
= render("actions")
#index-banner.parallax-container
  .parallax
    = image_tag("header/index.png")
.container
  .section
    .row
      = render("header")
    .row
      = form_for @user do |f|
        = f.hidden_field(:name)
        .col.xs12
          .card
            .card-content
              .row
                .input-field.col.xs12
                  = f.label :dob
                  = f.text_field :dob, class: 'validate'
                .input-field.col.xs12
                  = f.label :password
                  = f.password_field :password, class: 'validate'
                .input-field.col.xs12
                  = f.label :password_confirmation
                  = f.password_field :password_confirmation, class: 'validate'

        .col.s12
          .card
            .card-content
              => f.submit :class => "waves-effect waves-light btn green"
              = link_to "Zurück", user_path(@user.name), data: { confirm: t("helpers.submit.cancel_update", model: User.model_name.human) }, :class => "waves-effect waves-light btn red"

app/views/users/show.html.slim
= render("actions")
#index-banner.parallax-container
  .parallax
    = image_tag("header/index.png")
.container
  .section
    .row
      = render("header")
    - if !@user.friendships.empty?
      .row
        .col.s12
          .card
            .card-content
              span.card-title = User.human_attribute_name(:friends)
              .center-align
                - @user.sorted_friendships.each do |friendship|
                  - if friendship.status?
                    = link_to user_path(friendship.user.name) do
                      = image_tag("https://visage.surgeplay.com/bust/256/#{friendship.user.id}", alt: friendship.user.name, title: friendship.user.name, class: "circle", style: "height: 60px; margin: 15px;")

app/views/users/statistic.html.slim
= render("actions")
#index-banner.parallax-container
  .parallax= image_tag("header/index.png")
.container
  .section
    .row
      = render("header")
    .row
      .col.s12
        .card
          .card-content
            span.card-title = Bedwarsstatistic.model_name.human
            - if @statistic.nil?
              p Keine Daten gefunden...
            - else
              table.table
                thead
                  tr
                    th.center-align = Bedwarsstatistic.human_attribute_name(:score)
                    th.center-align = Bedwarsstatistic.human_attribute_name(:kd)
                    th.center-align = Bedwarsstatistic.human_attribute_name(:kills)
                    th.center-align = Bedwarsstatistic.human_attribute_name(:deaths)
                    th.center-align = Bedwarsstatistic.human_attribute_name(:games)
                    th.center-align = Bedwarsstatistic.human_attribute_name(:destroyed_beds)
                tbody
                  td.center-align = @statistic.score
                  td.center-align
                    - if @statistic.deaths != 0
                      = (@statistic.kills / @statistic.deaths).round
                    - else
                      = @statistic.kills
                  td.center-align = @statistic.kills
                  td.center-align = @statistic.deaths
                  td.center-align = (@statistic.wins + @statistic.loses)
                  td.center-align = @statistic.destroyedBeds

app/views/users/youtube.html.slim
= render("actions")
#index-banner.parallax-container
  .parallax
    = image_tag("header/index.png")
.container
  .section
    .row
      = render("header")
    .row
      .col.xs12
        .card.horizontal
          .card-image.valign-wrapper.col.xs4.hide-on-small-only[style="padding: 10px"]
            = link_to("https://www.youtube.com/channel/#{@channel.id}", target: :blank, class: "valign") do
              = image_tag(@channel.thumbnail_url(:high))
          .card-stacked.col.xs10.m9.l8
            .card-content
              span.card-title
                = @channel.title
              ul
                li
                  strong> Abonnenten:
                  = @channel.subscriber_count
                li
                  strong> Veröffentlichte Videos:
                  = @channel.video_count
              = link_to("https://www.youtube.com/channel/#{@channel.id}", {target: :blank, class: "waves-effect waves-light btn red"}) do
                => content_tag(:i, 'ondemand_video', class: 'material-icons left')
                | Zum Kanal
    .row
      - @videos.each do |video|
        .col.xs12.s6.l4
          .card
            .card-image
              = link_to("https://youtu.be/#{video.id}", target: :blank) do
                = image_tag(video.thumbnail_url(:high))