config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"

  get '/bewerbung' => 'static#application'
  get '/deine-chance' => 'static#youtube'
  get '/gamescom' => 'static#gamescom', :as => 'gamescom'
  
  localized do
    get "/404" => "errors#not_found"
    get "/422" => "errors#change_rejected"
    get "/500" => "errors#internal_server_error"
  
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection
    end
  
    concern :searchable do
      get 'search/:search', :action => :search, :on => :collection, as: 'search_result'
      post 'search/', :action => :search, :on => :collection, :as => 'search'
    end
  
    concern :search_paginatable do
      get 'search/:search/(page/:page)', :action => :search, :on => :collection
    end
  
    devise_for :users, path: 'account'
    get '/' => 'static#home', :as => 'home'
    get '/team' => 'static#team', :as => 'team'
    get '/your-chance' => 'static#youtube', :as => 'your_chance'
    get '/youtube' => 'static#youtube', :as => 'youtube'
    get '/team/history' => 'static#team_history', :as => 'team_history'
    get '/maps' => 'static#maps', :as => 'maps'
    get '/premium' => 'static#premium', :as => 'premium'
    get '/statistics' => 'static#statistic_bedwars', :as => 'statistics'
    get '/statistics/bedwars' => 'static#statistic_bedwars', :as => 'statistics_bedwars'
    get '/statistics/server' => 'static#statistic_server', :as => 'statistics_server'
    get '/statistics/location' => 'static#statistic_country', :as => 'statistics_country'
    get '/contact' => 'static#contact', :as => 'contact'
    get '/faq' => 'static#faq', :as => 'faq'
    get '/application' => 'static#application', :as => 'application'
    get '/imprint' => 'static#imprint', :as => 'imprint'
    get '/tos' => 'static#tos', :as => 'tos'
  
    resources :chatlogs, only: [:show]
  
    resources :users, path: 'players', except: [:edit, :update], param: :name, :concerns => [:searchable] do
      get 'statistic'
      get 'youtube'
    end
  
    resources :users, path: 'players/uuid/', only: [:edit]
    resources :users, path: 'players', only: [:update]
  
    get '/players/uuid/:id/' => 'users#show'
    get '/players/uuid/:id/statistic' => 'users#statistic'
    get '/players/uuid/:id/youtube' => 'users#youtube'
  
    get 'sitemap.xml' => 'sitemap#index'
  
    namespace :dashboard, layout: 'dashboard' do
      get '/' => 'users#online', :as => 'dashboard'
      resources :serverstatistics, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :chatlogs, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :users, path: 'players', :concerns => [:searchable, :search_paginatable, :paginatable] do
        get 'online', :on => :collection
        get 'chatlogs'
      end
    end
  end
  
  namespace :api do
    scope ':version' do
      resources :users, path: 'players', except: [:edit, :update], param: :name
      resources :serverstatistics, path: 'statistics', except: [:index, :edit, :update] do
        get 'online', :on => :collection
        get 'individual', :on => :collection
      end
    end
  end

end

app/views/shared/_flash.html.slim
- flash.each do |type, messages|
  color = ''
  - if type.start_with?("success","notice")
    - color = 'green'
  - elsif type.start_with?("error","alert")
    - color = 'red'
  - if messages.is_a? Enumerable
    - messages.each do |message|
      javascript:
        Materialize.toast("#{message}", 4000, "#{color}")
  - else
    javascript:
        Materialize.toast("#{messages}", 4000, "#{color}")

app/views/shared/_footer.html.slim
footer.page-footer
  - if user_signed_in?
    .fixed-action-btn[style="bottom: 45px; right: 24px;"]
      a.button-collapse.btn-floating.btn-large.show-on-large.bwnet.white-text.user-nav[href="#" data-activates="nav-user"]
        = content_tag(:i, 'person', class: 'material-icons')
  .container
    .row
      .col.l6.s12
        h5.white-text
          | bedwars.network
        p.grey-text.text-lighten-4 = t('global.footer.description')
      .col.offset-l3.l3.s12
        h5.white-text = t('global.footer.connect')
        ul
          li
            = link_to "Twitter", "https://www.twitter.com/bedwarsnetwork", target: "_blank", class: "white-text"
          li
            = link_to "Instagram", "https://www.instagram.com/bedwarsnetwork", target: "_blank", class: "white-text"
          li
            = link_to "Facebook", "https://www.facebook.com/bedwarsnetwork", target: "_blank", class: "white-text"
          li
            = link_to "YouTube", "https://www.youtube.com/bedwarsnetwork", target: "_blank", class: "white-text"
          li
            = link_to "E-Mail", "mailto:support@bedwars.network", target: "_blank", class: "white-text"
  .footer-copyright
    .container
      p
        |  &copy
        = Time.now.year
        |  bedwars.network |
        =<> link_to t('global.pages.imprint_and_privacy'), imprint_path(), class: "light-blue-text text-lighten-3"
        | |
        =<> link_to t('global.pages.tos'), tos_path(), class: "light-blue-text text-lighten-3"
        - if !user_signed_in?
          |  |
          =<> link_to "Anmelden", new_user_session_path(), class: "light-blue-text text-lighten-3"
        | | design based on
        =< link_to "Materialize", "https://materializecss.com", target: "_blank", class: "light-blue-text text-lighten-3"

app/views/shared/_head.html.slim
meta http-equiv="x-ua-compatible" content="ie=edge"
= display_meta_tags site: 'bedwars.network'
meta name="theme-color" content="#29b6f6"
meta name="application-name" content="bedwars.network"
meta name="apple-mobile-web-app-title" content="bedwars.net"
= csrf_meta_tags
= stylesheet_link_tag('application', 'https://fonts.googleapis.com/css?family=Ubuntu')
= stylesheet_link_tag('application', 'https://fonts.googleapis.com/css?family=Arvo')
= stylesheet_link_tag('application', 'https://fonts.googleapis.com/icon?family=Material+Icons')
= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')
= javascript_include_tag('application', 'data-turbolinks-track': 'reload')
= javascript_include_tag('//www.gstatic.com/charts/loader.js')
= favicon_link_tag('icons/apple-touch-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57')
= favicon_link_tag('icons/apple-touch-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x60')
= favicon_link_tag('icons/apple-touch-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72')
= favicon_link_tag('icons/apple-touch-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76')
= favicon_link_tag('icons/apple-touch-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114')
= favicon_link_tag('icons/apple-touch-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120')
= favicon_link_tag('icons/apple-touch-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144')
= favicon_link_tag('icons/apple-touch-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152')
= favicon_link_tag('icons/apple-touch-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180')
= favicon_link_tag('icons/favicon-16x16.png', rel: 'icon', type: 'image/png', sizes: '16x16')
= favicon_link_tag('icons/favicon-32x32.png', rel: 'icon', type: 'image/png', sizes: '32x32')
= favicon_link_tag('icons/favicon-96x96.png', rel: 'icon', type: 'image/png', sizes: '96x96')   
= favicon_link_tag('icons/android-chrome-192x192.png', rel: 'icon', type: 'image/png', sizes: '192x192')    
meta name="msapplication-square70x70logo" content="#{image_path('icons/smalltile.png')}"
meta name="msapplication-square150x150logo" content="#{image_path('icons/mediumtile.png')}"
meta name="msapplication-wide310x150logo" content="#{image_path('icons/widetile.png')}"
meta name="msapplication-square310x310logo" content="#{image_path('icons/largetile.png')}"
meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width"
meta name="apple-mobile-web-app-capable" content="yes"
meta name="apple-mobile-web-app-status-bar-style" content="translucent"
script[type="application/ld+json"]
  |
    {
      "@context": "http://schema.org",
      "@type": "WebSite",
      "name": "bedwars.network",
      "url": "https://www.bedwars.network",
      "potentialAction": {
        "@type": "SearchAction",
        "target": "https://www.bedwars.network/players/search/{search_term_string}",
        "query-input": "required name=search_term_string"
      }
    }
script[type="application/ld+json"]
  |
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "url": "http://www.bedwars.network",
      "logo": "http://static.bedwars.network/images/logo-square.png",
      "contactPoint": [{
        "@type": "ContactPoint",
        "email": "support@bedwars.network",
        "telephone": "+49 89 21543645",
        "contactType": "customer service"
      }],
      "sameAs": [
        "http://www.facebook.com/bedwarsnetwork",
        "http://www.twitter.com/bedwarsnetwork",
        "http://www.youtube.com/bedwarsnetwork",
        "http://plus.google.com/+bedwarsnetwork"
      ]
    }
javascript:
  Chartkick.configure({mapsApiKey: "#{ENV["GOOGLE_API_KEY"]}"})
- if Rails.env.production?
  = render "shared/piwik"

app/views/shared/_navigation.html.slim
.navbar-fixed
  nav[role="navigation"]
    .nav-wrapper.container
      = link_to "bedwars.network", home_path(), id: "logo-container", class: "brand-logo white-text"
      ul.right.hide-on-med-and-down
        li class=('active' if (params[:controller] == "static" && params[:action] == "team"))
          = link_to t('global.pages.team'), team_path(), class: "white-text"
        li class=('active' if (params[:controller] == "static" && params[:action] == "maps"))
            = link_to t('global.pages.maps'), maps_path(), class: "white-text"
        li class=('active' if (params[:controller] == "static" && params[:action] == "premium"))
            = link_to t('global.pages.premium'), premium_path(), class: "white-text"
        li class=('active' if (params[:controller] == "static" && params[:action] == "statistic"))
            = link_to t('global.pages.statistics'), statistics_path(), class: "white-text"
        li class=('active' if (params[:controller] == "static" && params[:action] == "faq"))
            = link_to t('global.pages.faq'), faq_path(), class: "white-text"
        li class=('active' if (params[:controller] == "static" && params[:action] == "contact"))
          = link_to t('global.pages.contact'), contact_path(), class: "white-text"
        li
          a[href="#!" class="dropdown-button" data-activates="language-dropdown"]
            = content_tag(:i, 'language', class: 'material-icons white-text')
      a.button-collapse.white-text.mobile-nav[href="#!" data-activates="nav-mobile"]
        i.material-icons
          | menu
ul#language-dropdown.dropdown-content
  li class=('active' if (I18n.locale == :de))
    = link_to(home_de_path()) do
      => image_tag('flags/de.png')
      | &nbsp;DE
    = link_to(home_en_path()) do
      => image_tag('flags/gb.png')
      | &nbsp;EN
ul#nav-mobile.side-nav
  li class=('active' if (params[:controller] == "static" && params[:action] == "home"))
    = link_to(home_path()) do
      = content_tag(:i, 'home', class: 'material-icons')
      = t('global.pages.home')
  li class=('active' if (params[:controller] == "static" && params[:action] == "team"))
    = link_to(team_path()) do
      = content_tag(:i, 'people', class: 'material-icons')
      = t('global.pages.team')
  li class=('active' if (params[:controller] == "static" && params[:action] == "maps"))
    = link_to(maps_path()) do
      = content_tag(:i, 'map', class: 'material-icons')
      = t('global.pages.maps')
  li class=('active' if (params[:controller] == "static" && params[:action] == "premium"))
    = link_to(premium_path()) do
      = content_tag(:i, 'star', class: 'material-icons')
      = t('global.pages.premium')
  li class=('active' if (params[:controller] == "static" && params[:action] == "statistic"))
    = link_to(statistics_path()) do
      = content_tag(:i, 'pie_chart', class: 'material-icons')
      = t('global.pages.statistics')
  li class=('active' if (params[:controller] == "static" && params[:action] == "faq"))
    = link_to(faq_path()) do
      = content_tag(:i, 'question_answer', class: 'material-icons')
      = t('global.pages.faq')
  li class=('active' if (params[:controller] == "static" && params[:action] == "contact"))
    = link_to(contact_path()) do
      = content_tag(:i, 'email', class: 'material-icons')
      = t('global.pages.contact')
- if user_signed_in?
  ul#nav-user.side-nav
    li
      .userView
        .bwnet.background
        = link_to(user_path(current_user.name)) do
          = image_tag("https://visage.surgeplay.com/bust/256/#{current_user.id}", class: "circle white")
        = link_to(user_path(current_user.name), class: "white-text") do
          = current_user.name
        - if current_user.rank
          .label.white-text style="background-color: ##{current_user.colorcode}"
            = current_user.rank
        - if current_user.online
          .label.green.white-text
            | online
    li class=('active' if (params[:controller] == "users" && params[:action] == "show" && params[:name] == current_user.name))
          = link_to(user_path(current_user.name)) do
            = content_tag(:i, 'person', class: 'material-icons')
            | Dein Profil
    li class=('active' if (params[:controller] == "users" && params[:action] == "statistic" && params[:name] == current_user.name))
          = link_to(user_statistic_path(current_user.name)) do
            = content_tag(:i, 'pie_chart', class: 'material-icons')
            | Deine Statistik
    - if can? :access, :dashboard
      li
        .divider[style="margin: 20px 0;"]
      li
          = link_to(online_dashboard_users_path()) do
            = content_tag(:i, 'dashboard', class: 'material-icons')
            | Dashboard
    - if content_for?(:actions)
      li
        .divider[style="margin: 20px 0;"]
      = yield(:actions)
    li
      .divider[style="margin: 20px 0;"]
    li
      = link_to(destroy_user_session_path, :method => :delete, class: "red white-text") do
        = content_tag(:i, 'clear', class: 'material-icons white-text')
        | Abmelden

app/views/shared/_piwik.html.slim
javascript:
  $(document).on('turbolinks:load', function() {
    if (window._paq != null) {
      _paq.push(['trackPageView']);
      _paq.push(['enableHeartBeatTimer']);
      _paq.push(['setCustomUrl', document.location]);
      _paq.push(['setDocumentTitle', document.title]);
    } else if (window.piwikTracker != null) {
      piwikTracker.trackPageview();
    }
  });
  var _paq = _paq || [];
  #{get_user_tracking_code.html_safe}
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  _paq.push(['enableHeartBeatTimer']);
  _paq.push(['setCustomUrl', document.location]);
  _paq.push(['setDocumentTitle', document.title]);
  (function() {
    var u="//#{ENV['PIWIK_URL']}/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', #{ENV['PIWIK_ID']}]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();