config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"

  get '/bewerbung' => 'static#application'
  get '/deine-chance' => 'static#youtube'
  get '/gamescom' => 'static#gamescom', :as => 'gamescom'
  
  localized do
    get "/404" => "errors#not_found"
    get "/422" => "errors#change_rejected"
    get "/500" => "errors#internal_server_error"
  
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection
    end
  
    concern :searchable do
      get 'search/:search', :action => :search, :on => :collection, as: 'search_result'
      post 'search/', :action => :search, :on => :collection, :as => 'search'
    end
  
    concern :search_paginatable do
      get 'search/:search/(page/:page)', :action => :search, :on => :collection
    end
  
    devise_for :users, path: 'account'
    get '/' => 'static#home', :as => 'home'
    get '/team' => 'static#team', :as => 'team'
    get '/your-chance' => 'static#youtube', :as => 'your_chance'
    get '/youtube' => 'static#youtube', :as => 'youtube'
    get '/team/history' => 'static#team_history', :as => 'team_history'
    get '/maps' => 'static#maps', :as => 'maps'
    get '/premium' => 'static#premium', :as => 'premium'
    get '/statistics' => 'static#statistic_bedwars', :as => 'statistics'
    get '/statistics/bedwars' => 'static#statistic_bedwars', :as => 'statistics_bedwars'
    get '/statistics/server' => 'static#statistic_server', :as => 'statistics_server'
    get '/statistics/location' => 'static#statistic_country', :as => 'statistics_country'
    get '/contact' => 'static#contact', :as => 'contact'
    get '/faq' => 'static#faq', :as => 'faq'
    get '/application' => 'static#application', :as => 'application'
    get '/imprint' => 'static#imprint', :as => 'imprint'
    get '/tos' => 'static#tos', :as => 'tos'
  
    resources :chatlogs, only: [:show]
  
    resources :users, path: 'players', except: [:edit, :update], param: :name, :concerns => [:searchable] do
      get 'statistic'
      get 'youtube'
    end
  
    resources :users, path: 'players/uuid/', only: [:edit]
    resources :users, path: 'players', only: [:update]
  
    get '/players/uuid/:id/' => 'users#show'
    get '/players/uuid/:id/statistic' => 'users#statistic'
    get '/players/uuid/:id/youtube' => 'users#youtube'
  
    get 'sitemap.xml' => 'sitemap#index'
  
    namespace :dashboard, layout: 'dashboard' do
      get '/' => 'users#online', :as => 'dashboard'
      resources :serverstatistics, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :chatlogs, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :users, path: 'players', :concerns => [:searchable, :search_paginatable, :paginatable] do
        get 'online', :on => :collection
        get 'chatlogs'
      end
    end
  end
  
  namespace :api do
    scope ':version' do
      resources :users, path: 'players', except: [:edit, :update], param: :name
      resources :serverstatistics, path: 'statistics', except: [:index, :edit, :update] do
        get 'online', :on => :collection
        get 'individual', :on => :collection
      end
    end
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  skip_authorization_check

  def index
    if params[:page].nil?
      params[:page] = 1
    end
    @users = User.order_by(:name => 'asc').page params[:page]
    @metadata[:total] = User.count
    respond_with @users, :api_template => @api_template, :root => :users, :meta => @metadata
  end
  
  def show
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
     respond_with @user, :api_template => @api_template, :location => user_path(@user)
  end

end

app/controllers/dashboard/chatlogs_controller.rb
class Dashboard::ChatlogsController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
		@chatlogs = Chatlog.order_by(:created => 'desc').page params[:page]
		@active_chatlogs = Chatlog.where(:complete => false).order_by(:created => 'desc').page params[:page]
		@page_title = "Chatlogs"
  end
  
  def search
    if params[:search].empty?
      redirect_to dashboard_chatlogs_path()
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_chatlogs_path(params[:search])
    elsif params[:search] && request.get?
      @page_title = ["Chatlogs", "Suche", params[:search]]
      @chatlogs = Chatlog.where({_id: /.*#{params[:search]}.*/i }).order_by(:created => 'desc').page params[:page]
      if @chatlogs.count == 1
        redirect_to dashboard_chatlog_path(@chatlogs.first.id)
      else
        render 'index'
      end
		end
	end
  
	def show
    @chatlog = Chatlog.find_by(_id: params[:id])
    if @chatlog.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Chatlog nicht gefunden" })
    end
    @page_title = ["Chatlog", @chatlog.id]
	end
	
	private
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/dashboard/serverstatistics_controller.rb
class Dashboard::ServerstatisticsController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
    @page_title = "Serverstatistik"
    @serverstatistics = Serverstatistic.order_by(:_id => 'desc').page params[:page]
  end
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, Serverstatistic))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_serverstatistics_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @serverstatistics.count == 1
        redirect_to dashboard_serverstatistics_path(@serverstatistics.first)
      else
        @page_title = ["Server-Statistik", "Suche", params[:search]]
        render 'index'
      end
		end
	end
  	
	def show
    if(params[:id] == "today")
  	 @serverstatistic = Serverstatistic.find_by(id: DateTime.now.in_time_zone("Berlin").strftime("%Y-%m-%d"))
    else
      @serverstatistic = Serverstatistic.find_by(id: params[:id])
    end
    if @serverstatistic.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Statistik nicht gefunden" })
    end
    @page_title = ["Server-Statistik", @serverstatistic._id.in_time_zone("Berlin").strftime("%A, %d.%m.%Y")]
	end

	
	private
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
    @page_title = "Spieler"
    @users = User.order_by(:name => 'asc').page params[:page]
  end
  
  def online
    @page_title = "Spieler online"
    @users = User.where({:online => true }).order_by(:name => 'asc').page params[:page]
    user_ips = []
    @users.each{|player| user_ips << player.sorted_sessions.first.ip_address}
    @second_account_ip_groups = User.where({:'sessions.ip_address'.in => user_ips}).order_by(:lastSeen => 'desc').group_by{|player| player.sorted_sessions.first.ip_address}.to_a.reverse.to_h
  end
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, User))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_users_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" },
          {name: /.*#{params[:search]}.*/i }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @users.count == 1
        redirect_to dashboard_user_path(@users.first)
      else
        @page_title = ["Spieler", "Suche", params[:search]]
        render 'index'
      end
		end
	end
  	
	def show
      @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name]
	end
	
	def chatlogs
    @user = User.find_by(id: params[:user_id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Chatlogs"]
    @chatlogs = Chatlog.where({"messages.user_id": @user._id }).order_by(:created => 'desc').page params[:page]
	end
	
	def edit
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
	end
	
	def update
		if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
		if needs_password?(@user, user_params)
      if @user.update(user_params)
        if(@user == current_user)
          bypass_sign_in(@user)
        end
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    else
  		if @user.update_without_password(user_params)
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    end
    flash[:error] = ["Fehler beim Speichern"]
    @user.errors.full_messages.each do |msg|
      flash[:error] << msg
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
		render 'edit'
	end
	
	private
	
	  def needs_password?(user, user_params)
			!user_params[:password].blank?
    end
    
		def user_params
			params.require(:user).permit(:youtube_id, :password, :password_confirmation, :team_member_since, :team_member_until)
		end
		
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit]
  load_and_authorize_resource
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, User))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_users_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" },
          {name: /.*#{params[:search]}.*/i }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @users.count == 1
        redirect_to user_path(@users.first.name)
      else
        redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
        return
      end
		end
	end
  
  def statistic
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:user_name)
      @user = User.find_by(name: params[:user_name])      
      #@lhplayer = Leaderheadsplayer.where(uuid: @user._id).first
      #@lhmonthlystatistic = @lhplayer.leaderheadsmonthlystatistics.group_by{|statistic| [statistic.year, statistic.month]}.sort_by{|statistic| [0, 1]}.reverse_each
      #@lhdailystatistic = @lhplayer.leaderheadsdailystatistics.group_by{|statistic| statistic.day}.sort_by{|statistic| 0}.reverse_each
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    else
      @statistic = Bedwarsstatistic.where(uuid: @user._id).first
    end
    @page_title = ["Spieler", @user.name, "Statistik"]
    @page_description = "Bestaune die Bedwars-Statistik von #{@user.name}."
	end
	
	def show
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    @page_title = ["Spieler", @user.name]
    @page_description = "Informiere dich über den Spieler #{@user.name}."
    respond_to do |format|
      format.html # index.html.erb
      format.json { render_for_api :name_only, json: @user }
    end
	end
	
	def youtube
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:user_name)
      @user = User.find_by(name: params[:user_name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    if @user.youtube_id.nil? || @user.youtube_id.empty?
      redirect_back(fallback_location: home_path, :flash => { :error => "YouTube nicht gefunden" })
      return
    end
    @channel = Yt::Channel.new id: @user.youtube_id
    begin
      @channel.title # Check if channel exists
      @videos = Yt::Collections::Videos.new
      @videos.where(channel_id: @user.youtube_id, q: "bedwars.network")
    rescue => e
      redirect_back(fallback_location: home_path, :flash => { :error => "YouTube nicht gefunden" })
      return
    end 
    @page_title = ["Spieler", @user.name, "YouTube-Kanal"]
    @page_description = "Siehe dir die Videos an, die #{@user.name} auf bedwars.network aufgenommen hat."
	end
	
	def edit
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
	end
	
	def update
		if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
      return
    end
    if needs_password?(@user, user_params)
      if @user.update(user_params)
        if(@user == current_user)
          bypass_sign_in(@user)
        end
  			redirect_to user_path(@user.name), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    else
  		if @user.update_without_password(user_params)
  			redirect_to user_path(@user.name), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    end
    flash[:error] = ["Fehler beim Speichern"]
    @user.errors.full_messages.each do |msg|
      flash[:error] << msg
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
		render 'edit'
	end
	
	private
	
	  def needs_password?(user, user_params)
			!user_params[:password].blank?
    end
    
		def user_params
			params.require(:user).permit(:youtube_id, :name, :password, :password_confirmation)
		end
end

app/views/dashboard/users/_actions.html.slim
- content_for :actions do
    li
      a.subheader
        => User.model_name.human
        = @user.name
      li class=('active' if (params[:controller] == "dashboard/users") && params[:action] == "chatlogs")
        = link_to(user_path(@user.name)) do
          = content_tag(:i, 'person', class: 'material-icons')
          = User.model_name.human(count: 2)
    - if (can? :index, Chatlog) || (can? :chatlogs, User)
      li class=('active' if (params[:controller] == "dashboard/users") && params[:action] == "chatlogs")
        = link_to(dashboard_user_chatlogs_path(@user)) do
          = content_tag(:i, 'attach_file', class: 'material-icons')
          = Chatlog.model_name.human(count: 2)
    - if can? :update, @user
      li class=('active' if (params[:controller] == "users" && params[:action] == "edit" && params[:id] == @user.id))
        = link_to(edit_dashboard_user_path(@user)) do
          = content_tag(:i, 'mode_edit', class: 'material-icons')
          | Bearbeiten

app/views/dashboard/users/_header.html.slim
.row
  .col.xs12
    .card.collection.z-depth-0
      .card-content.center-align
        h1 style=("text-transform: none") = @user.name
        - if @user.rank
          = content_tag(:div, class: "chip white-text", style: "background-color: ##{@user.colorcode}") do
            = @user.rank
        - if @user.online
          .chip.green.white-text
            | online

app/views/dashboard/users/_searchbar.html.slim
- content_for :searchbar do
  li.search
    .search-wrapper.card
      = form_tag(search_dashboard_users_path(), :method => 'post') do
        = text_field_tag :search, params[:search]
        = content_tag(:i, "search", class: "material-icons")
    .clearfix

app/views/dashboard/users/_user.html.slim
tr
  td
    = link_to dashboard_user_path(user) do
      span.title = user.name
  td
    - if user.online
      .label.green.white-text
        - if user.last_location
          = user.last_location
        - else
          | online 
    - elsif user.sessions.last.end
      = user.sessions.last.end.in_time_zone("Berlin").strftime("%d.%m.%Y - %H:%M Uhr")
  td
    - if user.statistic
      = (user.statistic.wins + user.statistic.loses)
    - else
      | 0
  td
    - if user.rank
      => content_tag(:span, class: "label white-text", style: "background-color: ##{user.colorcode}") do
        = user.rank
    - if user.bans.size > 0 and can? :ban, user
      - if user.is_banned
        .label.red.white-text
          | gebannt
      - else
        span.label.orange.white-text
          | Hat Bannhistorie

app/views/dashboard/users/chatlogs.html.slim
= render("actions")
= render("searchbar")
.row
  = render("header")
.row
  .col.xs12
    - if @chatlogs.empty?
      .card.collection.z-depth-0
        .card-content
          | Keine Chatlogs gefunden...
    - else
      .center-align
        = paginate @chatlogs
      ul.collection
        - @chatlogs.each do |chatlog|
          li.collection-item.avatar
            = link_to dashboard_chatlog_path(chatlog) do
              = content_tag(:i, chatlog.server_icon, class: "material-icons #{chatlog.server_icon_color} circle")
              - if params[:search]
                  span.title = highlight(chatlog._id, params[:search])
              - else
                span.title = chatlog._id
              p
                span.grey-text.lighten-2
                  = chatlog.server
                  |  - 
                  = chatlog.created.in_time_zone("Berlin").strftime("%d.%m.%Y - %H:%M Uhr")
                br
                span.grey-text.lighten-2
                  = chatlog.messages.count
                  |  Elemente
              .secondary-content
                = content_tag(:i, "attachment", class: "material-icons")
        .center-align
          = paginate @chatlogs

app/views/dashboard/users/edit.html.slim
= render("actions")
= render("searchbar")
.row
  = render("header")
.row
  = form_for [:dashboard, @user] do |f|
    .col.xs12
      .card.collection.z-depth-0
        .card-content
          .row
            .input-field.col.xs12
              = f.label :youtube_id
              = f.text_field :youtube_id, class: 'validate'
          .row
            .input-field.col.xs12
              = f.label :password
              = f.password_field :password, class: 'validate'
            .input-field.col.xs12
              = f.label :password_confirmation
              = f.password_field :password_confirmation, class: 'validate'
          .row
            .input-field.col.xs12
              = f.label :team_member_since
              = f.date_field :team_member_since, class: 'datepicker'
            - if @user.team_member_since
              .input-field.col.xs12
                = f.label :team_member_until
                = f.date_field :team_member_until, class: 'datepicker'
    .col.s12
      .card.collection.z-depth-0
        .card-content
          => f.submit :class => "waves-effect waves-light btn green"
          = link_to "Zurück", dashboard_user_path(@user), data: { confirm: t("helpers.submit.cancel_update", model: User.model_name.human) }, :class => "waves-effect waves-light btn red"

app/views/dashboard/users/index.html.slim
= render("searchbar")
.row
  .col.xs12
    .card.collection.z-depth-0
      .card-content.center-align
        h1 = User.model_name.human(count: 2)
.row
  .col.xs12
    .card.collection.z-depth-0
      .card-content
        - if @users.empty?
              | Keine Spieler gefunden...
        - else
          .center-align
            = paginate @users
          table
            thead
              th Spielername
              th Zuletzt gesehen
              th Gespielte Spiele
              th
            tbody  
              = render @users
          .center-align
            = paginate @users

app/views/dashboard/users/online.html.slim
= render("searchbar")
.section
  .row
    .col.xs12
      ul.collection.with-header
        li.collection-header.center-align
          h1
            => User.model_name.human(count: 2)
            | online
.section
  .row
    .col.xs12
      .card.collection.z-depth-0
        .card-content
          - if @users.empty?
            | Keine Spieler online...
          - else
            table
              thead
                th Spielername
                th Zuletzt gesehen
                th Gespielte Spiele
                th
              tbody  
                = render @users
- if !@users.empty? and can? :ban, User
  .divider
  .section
    .row
      .col.xs12
        ul.collection.with-header
          li.collection-header.center-align
            h4 Etwaige Zweitaccounts
    .row
      - @second_account_ip_groups.each do |ip, users|
        - if users.count > 1
          .col.xs12
            .card.collection.z-depth-0
              .card-content
                - if can? :ip, session
                  h5 = ip
                - else
                  - splitted_ip = ip.split('.')
                  h5 #{splitted_ip[0]}.#{splitted_ip[1]}.#{splitted_ip[2]}.XXX
                table
                  thead
                    th Spielername
                    th Zuletzt gesehen
                    th Gespielte Spiele
                    th
                  tbody
                  = render users

app/views/dashboard/users/show.html.slim
= render("actions")
= render("searchbar")
.row
  = render("header")
- if !@user.bans.empty? and can? :ban, User
  .row
    .col.xs12
      .card.collection.z-depth-0
        .card-content
          span.card-title Bans
          .center-align
          table
            thead
              th
              th Datum
              th Grund
              th Ende
            tbody    
              - @user.bans.each do |ban|
                = render ban
- if !@user.sessions.empty? and can? :ban, User
  .row
    .col.xs12
      .card.collection.z-depth-0
        .card-content
          span.card-title Sessions
          .center-align
          table
            thead
              th Start
              th IP
              th Ort
              th Ende
            tbody    
              - @user.sorted_sessions.take(10).each do |session|
                = render session
- if !@user.friendships.empty?
  .row
    .col.xs12
      .card.collection.z-depth-0
        .card-content
          span.card-title Freunde
          .center-align
          table
            thead
              th Spielername
              th Zuletzt gesehen
              th Gespielte Spiele
              th
            tbody    
              - @user.sorted_friendships.each do |friendship|
                - if friendship.status?
                  = render friendship.user