config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"

  get '/bewerbung' => 'static#application'
  get '/deine-chance' => 'static#youtube'
  get '/gamescom' => 'static#gamescom', :as => 'gamescom'
  
  localized do
    get "/404" => "errors#not_found"
    get "/422" => "errors#change_rejected"
    get "/500" => "errors#internal_server_error"
  
    concern :paginatable do
      get '(page/:page)', :action => :index, :on => :collection
    end
  
    concern :searchable do
      get 'search/:search', :action => :search, :on => :collection, as: 'search_result'
      post 'search/', :action => :search, :on => :collection, :as => 'search'
    end
  
    concern :search_paginatable do
      get 'search/:search/(page/:page)', :action => :search, :on => :collection
    end
  
    devise_for :users, path: 'account'
    get '/' => 'static#home', :as => 'home'
    get '/team' => 'static#team', :as => 'team'
    get '/your-chance' => 'static#youtube', :as => 'your_chance'
    get '/youtube' => 'static#youtube', :as => 'youtube'
    get '/team/history' => 'static#team_history', :as => 'team_history'
    get '/maps' => 'static#maps', :as => 'maps'
    get '/premium' => 'static#premium', :as => 'premium'
    get '/statistics' => 'static#statistic_bedwars', :as => 'statistics'
    get '/statistics/bedwars' => 'static#statistic_bedwars', :as => 'statistics_bedwars'
    get '/statistics/server' => 'static#statistic_server', :as => 'statistics_server'
    get '/statistics/location' => 'static#statistic_country', :as => 'statistics_country'
    get '/contact' => 'static#contact', :as => 'contact'
    get '/faq' => 'static#faq', :as => 'faq'
    get '/application' => 'static#application', :as => 'application'
    get '/imprint' => 'static#imprint', :as => 'imprint'
    get '/tos' => 'static#tos', :as => 'tos'
  
    resources :chatlogs, only: [:show]
  
    resources :users, path: 'players', except: [:edit, :update], param: :name, :concerns => [:searchable] do
      get 'statistic'
      get 'youtube'
    end
  
    resources :users, path: 'players/uuid/', only: [:edit]
    resources :users, path: 'players', only: [:update]
  
    get '/players/uuid/:id/' => 'users#show'
    get '/players/uuid/:id/statistic' => 'users#statistic'
    get '/players/uuid/:id/youtube' => 'users#youtube'
  
    get 'sitemap.xml' => 'sitemap#index'
  
    namespace :dashboard, layout: 'dashboard' do
      get '/' => 'users#online', :as => 'dashboard'
      resources :serverstatistics, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :chatlogs, :concerns => [:searchable, :search_paginatable, :paginatable]
      resources :users, path: 'players', :concerns => [:searchable, :search_paginatable, :paginatable] do
        get 'online', :on => :collection
        get 'chatlogs'
      end
    end
  end
  
  namespace :api do
    scope ':version' do
      resources :users, path: 'players', except: [:edit, :update], param: :name
      resources :serverstatistics, path: 'statistics', except: [:index, :edit, :update] do
        get 'online', :on => :collection
        get 'individual', :on => :collection
      end
    end
  end

end

app/controllers/dashboard/chatlogs_controller.rb
class Dashboard::ChatlogsController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
		@chatlogs = Chatlog.order_by(:created => 'desc').page params[:page]
		@active_chatlogs = Chatlog.where(:complete => false).order_by(:created => 'desc').page params[:page]
		@page_title = "Chatlogs"
  end
  
  def search
    if params[:search].empty?
      redirect_to dashboard_chatlogs_path()
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_chatlogs_path(params[:search])
    elsif params[:search] && request.get?
      @page_title = ["Chatlogs", "Suche", params[:search]]
      @chatlogs = Chatlog.where({_id: /.*#{params[:search]}.*/i }).order_by(:created => 'desc').page params[:page]
      if @chatlogs.count == 1
        redirect_to dashboard_chatlog_path(@chatlogs.first.id)
      else
        render 'index'
      end
		end
	end
  
	def show
    @chatlog = Chatlog.find_by(_id: params[:id])
    if @chatlog.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Chatlog nicht gefunden" })
    end
    @page_title = ["Chatlog", @chatlog.id]
	end
	
	private
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/dashboard/serverstatistics_controller.rb
class Dashboard::ServerstatisticsController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
    @page_title = "Serverstatistik"
    @serverstatistics = Serverstatistic.order_by(:_id => 'desc').page params[:page]
  end
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, Serverstatistic))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_serverstatistics_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @serverstatistics.count == 1
        redirect_to dashboard_serverstatistics_path(@serverstatistics.first)
      else
        @page_title = ["Server-Statistik", "Suche", params[:search]]
        render 'index'
      end
		end
	end
  	
	def show
    if(params[:id] == "today")
  	 @serverstatistic = Serverstatistic.find_by(id: DateTime.now.in_time_zone("Berlin").strftime("%Y-%m-%d"))
    else
      @serverstatistic = Serverstatistic.find_by(id: params[:id])
    end
    if @serverstatistic.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Statistik nicht gefunden" })
    end
    @page_title = ["Server-Statistik", @serverstatistic._id.in_time_zone("Berlin").strftime("%A, %d.%m.%Y")]
	end

	
	private
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!, :verify_access
  load_and_authorize_resource
  
  def index
    @page_title = "Spieler"
    @users = User.order_by(:name => 'asc').page params[:page]
  end
  
  def online
    @page_title = "Spieler online"
    @users = User.where({:online => true }).order_by(:name => 'asc').page params[:page]
    user_ips = []
    @users.each{|player| user_ips << player.sorted_sessions.first.ip_address}
    @second_account_ip_groups = User.where({:'sessions.ip_address'.in => user_ips}).order_by(:lastSeen => 'desc').group_by{|player| player.sorted_sessions.first.ip_address}.to_a.reverse.to_h
  end
  
  def search
    if params[:search].empty? || (params[:search].to_s.length < 3 && !(can? :index, User))
      redirect_back(fallback_location: home_path, :flash => { :error => "Suchbegriff zu kurz" })
    elsif params[:search] && request.post?
      redirect_to search_result_dashboard_users_path(params[:search])
    elsif params[:search] && request.get?
      @users = User.where({
        "$or" => [
          {_id: "#{params[:search]}" },
          {name: /.*#{params[:search]}.*/i }
        ]
      }).order_by(:name => 'asc').page params[:page]
      if @users.count == 1
        redirect_to dashboard_user_path(@users.first)
      else
        @page_title = ["Spieler", "Suche", params[:search]]
        render 'index'
      end
		end
	end
  	
	def show
      @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name]
	end
	
	def chatlogs
    @user = User.find_by(id: params[:user_id])
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Chatlogs"]
    @chatlogs = Chatlog.where({"messages.user_id": @user._id }).order_by(:created => 'desc').page params[:page]
	end
	
	def edit
    if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
	end
	
	def update
		if params.has_key?(:id)
      @user = User.find_by(id: params[:id])
    elsif params.has_key?(:name)
      @user = User.find_by(name: params[:name])
    end
    if @user.nil?
      redirect_back(fallback_location: home_path, :flash => { :error => "Spieler nicht gefunden" })
    end
		if needs_password?(@user, user_params)
      if @user.update(user_params)
        if(@user == current_user)
          bypass_sign_in(@user)
        end
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    else
  		if @user.update_without_password(user_params)
  			redirect_to dashboard_user_path(@user), :flash => { :success => "Spieler gespeichert" }
  			return
  		end
    end
    flash[:error] = ["Fehler beim Speichern"]
    @user.errors.full_messages.each do |msg|
      flash[:error] << msg
    end
    @page_title = ["Spieler", @user.name, "Bearbeiten"]
		render 'edit'
	end
	
	private
	
	  def needs_password?(user, user_params)
			!user_params[:password].blank?
    end
    
		def user_params
			params.require(:user).permit(:youtube_id, :password, :password_confirmation, :team_member_since, :team_member_until)
		end
		
  def verify_access
    redirect_back(fallback_location: home_path) unless can? :access, :dashboard
  end
end

app/views/shared/dashboard/_footer.html.slim
footer
  .fixed-action-btn[style="bottom: 45px; right: 24px;"]
    a.button-collapse.btn-floating.btn-large.bwnet.hide-on-large-and-up.white-text.mobile-nav[href="#" data-activates="nav-dashboard"]
      = content_tag(:i, 'menu', class: 'material-icons')

app/views/shared/dashboard/_navigation.html.slim
ul#nav-dashboard.side-nav.fixed
  li
    .userView.center-align
      .bwnet.background
      h3.white-text
        | Dashboard
  - if content_for?(:searchbar)
      = yield(:searchbar)
      li
        .divider[style="margin: 20px 0;"]
  li.no-padding
    ul.collapsible.collapsible-accordion
      li
        = link_to(home_path()) do
          = content_tag(:i, 'home', class: 'material-icons')
          | Zur Website
      - if can? :online, User or can? :index, Chatlog or can? :index, User or can? :index, Serverstatistic
        li
          .divider
        li
          a.subheader
            | Intern
      - if can? :online, User
        li class=('active' if (params[:controller] == "dashboard/users" && params[:action] == "online"))
          = link_to(online_dashboard_users_path()) do
            = content_tag(:i, 'dashboard', class: 'material-icons')
            => Dashboard
      - if can? :index, User
        li class=('active' if (params[:controller] == "dashboard/users" && (params[:action] == "index" || params[:action] == "search")))
          = link_to(dashboard_users_path()) do
            = content_tag(:i, 'people', class: 'material-icons')
            => User.model_name.human
      - if can? :index, Chatlog
         li class=('active' if (params[:controller] == "dashboard/chatlogs"))
            = link_to(dashboard_chatlogs_path()) do
              = content_tag(:i, 'attach_file', class: 'material-icons')
              = Chatlog.model_name.human(count: 2)
      - if can? :index, Serverstatistic
         li class=('active' if (params[:controller] == "dashboard/serverstatistics"))
            = link_to(dashboard_serverstatistics_path()) do
              = content_tag(:i, 'pie_chart', class: 'material-icons')
              = Serverstatistic.model_name.human(count: 2)
      - if content_for?(:actions)
        .divider[style="margin: 20px 0;"]
        = yield(:actions)
      li
        .divider[style="margin: 20px 0;"]
      li
        = link_to(destroy_user_session_path, :method => :delete, class: "red white-text") do
          = content_tag(:i, 'clear', class: 'material-icons white-text')
          | Abmelden